# Generated by Django 4.1.4 on 2022-12-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirm_code',
            field=models.CharField(blank=True, default='', max_length=129, null=True),
        ),
    ]
